title: 日米メガネ連合・LPG-UJ 
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://glassesleague.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github:
   twitter:
   facebook: 
   email: glassesleague@gmail.com

#google_analytics: "UA-58263416-1"
